import { OmitType } from "@nestjs/mapped-types";
import { IsDateString, IsEnum, IsOptional } from "class-validator";
import { PaymentMethod, Recurrence } from "@wealthos/db";
import { CreateExpenseDto, IsNotFarFutureDate } from "./create-expense.dto";

// Quick Expense: the fewest fields that make an expense, with sensible defaults so it can be
// saved in seconds. Amount, category, merchant/description, notes and the classification
// (flowType) are inherited from CreateExpenseDto so their validation can never drift apart.
export class QuickExpenseDto extends OmitType(CreateExpenseDto, ["spentAt", "paymentMethod", "isRecurring"] as const) {
  // Defaults to today (UTC calendar day). Clients should send their own local date.
  @IsOptional()
  @IsDateString()
  @IsNotFarFutureDate(1)
  spentAt?: string;

  // Defaults to UPI, the most common method.
  @IsOptional()
  @IsEnum(PaymentMethod)
  paymentMethod?: PaymentMethod;

  // "Repeat?" — omit or ONE_TIME for a single expense. The saved row becomes the recurrence
  // template and later occurrences are generated by the existing recurrence engine, never in
  // advance (no future "actual" rows).
  @IsOptional()
  @IsEnum(Recurrence)
  recurrence?: Recurrence;

  @IsOptional()
  @IsDateString()
  recurrenceEndDate?: string;
}
