// Shared domain types used across apps/api and apps/web.
// Kept framework-agnostic (no Prisma/Nest/React imports) so both can consume it safely.

export type Role = "OWNER" | "MEMBER";
export type TaxRegime = "OLD" | "NEW";
export type RiskProfile = "CONSERVATIVE" | "MODERATE" | "AGGRESSIVE";
export type CategoryType = "NEED" | "WANT" | "SAVINGS";
export type CoachPlanType = "DEBT_PAYOFF" | "SAVINGS_TARGET" | "RETIREMENT" | "INVESTMENT_ALLOCATION" | "CUSTOM";
export type CoachPlanStatus = "ACTIVE" | "AT_RISK" | "COMPLETED" | "ABANDONED";
export type CoachStepStatus = "PENDING" | "IN_PROGRESS" | "DONE" | "SKIPPED";
export type CoachTaskStatus = "OPEN" | "DONE" | "DISMISSED";
export type CoachNudgeSeverity = "INFO" | "WARNING" | "CRITICAL";

export interface CoachPlanStepDTO {
  id: string;
  sequence: number;
  description: string;
  dueDate: string | null;
  status: CoachStepStatus;
  completedAt: string | null;
}

export interface CoachPlanDTO {
  id: string;
  type: CoachPlanType;
  title: string;
  objective: string;
  targetMetricType: string;
  targetValue: string;
  targetDate: string;
  startingValue: string;
  currentValue: string;
  status: CoachPlanStatus;
  lastCheckedAt: string | null;
  createdAt: string;
  steps?: CoachPlanStepDTO[];
}

export interface CoachTaskDTO {
  id: string;
  planId: string | null;
  title: string;
  detail: string;
  dueDate: string | null;
  status: CoachTaskStatus;
  createdAt: string;
  completedAt: string | null;
}

export interface CoachNudgeDTO {
  id: string;
  planId: string | null;
  severity: CoachNudgeSeverity;
  message: string;
  dismissed: boolean;
  createdAt: string;
}

export type IncomeSource =
  | "SALARY"
  | "FREELANCE"
  | "BUSINESS"
  | "RENT"
  | "DIVIDEND"
  | "INTEREST"
  | "BONUS"
  | "PENSION"
  | "OTHER";
export type Recurrence = "ONE_TIME" | "WEEKLY" | "BIWEEKLY" | "MONTHLY" | "QUARTERLY" | "YEARLY";
export type PaymentMethod = "CASH" | "UPI" | "CARD" | "BANK_TRANSFER" | "WALLET" | "OTHER";

export interface UserDTO {
  id: string;
  email: string;
  phone: string | null;
  name: string | null;
  role: Role;
  householdId: string | null;
  taxRegime: TaxRegime;
  riskProfile: RiskProfile;
  createdAt: string;
}

export interface HouseholdDTO {
  id: string;
  name: string;
  members: UserDTO[];
  dependents: DependentDTO[];
}

export interface DependentDTO {
  id: string;
  householdId: string;
  name: string;
  relation: string;
  dateOfBirth: string | null;
}

export interface IncomeDTO {
  id: string;
  userId: string;
  source: IncomeSource;
  label: string;
  amount: string; // decimal serialized as string to avoid float precision issues
  currency: string;
  recurrence: Recurrence;
  receivedAt: string;
  notes: string | null;
  // NEW (audit item #3): opt-in recurring-generation fields. recurrenceActive
  // defaults to false for every row, including all pre-existing ones — nothing
  // auto-generates unless the user explicitly turns it on.
  recurrenceActive: boolean;
  recurrenceEndDate: string | null;
  nextOccurrenceAt: string | null;
  // Set only on rows that were themselves auto-generated by RecurrenceGeneratorService
  // — null on every manually-entered row (i.e. every row that existed before this
  // feature, and any row a user adds by hand going forward).
  generatedFromRecurringId: string | null;
}

// NEW (audit item #4): one entry per logged amount change on an Income row — see
// IncomeService.update()'s doc comment for exactly when these are created.
export interface IncomeHistoryDTO {
  id: string;
  userId: string;
  incomeId: string;
  previousAmount: string;
  newAmount: string;
  effectiveFrom: string;
  createdAt: string;
}

export interface CategoryDTO {
  id: string;
  name: string;
  type: CategoryType;
  icon: string | null;
  isSystem: boolean;
}

export interface ExpenseDTO {
  id: string;
  userId: string;
  categoryId: string;
  category?: CategoryDTO;
  merchant: string | null;
  amount: string;
  currency: string;
  spentAt: string;
  paymentMethod: PaymentMethod;
  notes: string | null;
  isRecurring: boolean;
  // NEW (audit item #3): recurrence is a genuinely new field — Expense previously had
  // no cadence at all, only the isRecurring boolean above (untouched). Null means "no
  // cadence set," which is every pre-existing row's state. The other three fields
  // mirror IncomeDTO's — see its doc comment above for what each means.
  recurrence: Recurrence | null;
  recurrenceActive: boolean;
  recurrenceEndDate: string | null;
  nextOccurrenceAt: string | null;
  generatedFromRecurringId: string | null;
  // Absent on rows from older API versions; treat missing as "EXPENSE".
  flowType?: ExpenseFlowType;
  // Values future occurrences are generated with (null = the row's own values). Only set on a
  // recurrence template that has had its rule edited.
  recurrenceTemplate?: ExpenseRuleValuesDTO | null;
}

export interface CategoryBreakdownDTO {
  categoryId: string;
  name: string;
  type: CategoryType;
  total: number;
}

// NOTE: "Subscriptions" is intentionally NOT a first-class trackable entity — there is
// no Subscription model. This is a derived, heuristic view over Expense rows (see
// ExpensesService.detectSubscriptions). See README "Subscriptions" section for the
// reasoning behind that decision.
export type SubscriptionConfidence = "LOW" | "MEDIUM" | "HIGH";

export interface DetectedSubscriptionDTO {
  merchant: string;
  occurrences: number;
  averageAmount: number;
  confidence: SubscriptionConfidence;
  lastSeenAt: string;
  sourceExpenseIds: string[];
}

export interface FinancialHealthScoreDTO {
  score: number;
  breakdown: {
    savingsRate: number;
    debtToIncome: number;
    emergencyFundMonths: number;
    // Previously always 100 (a hardcoded placeholder — see the audit's flagged gap).
    // Now a real, budget-amount-weighted score computed from the user's own
    // per-category budgets whenever budgetAdherenceIsReal is true. When it's false
    // (no budgets configured), this still reports 100 for calculation continuity, but
    // is NOT weighted into `score` above and should not be displayed as a meaningful
    // figure on its own — see budgetAdherenceIsReal.
    budgetAdherence: number;
  };
  band: "STRONG" | "STABLE" | "NEEDS_ATTENTION" | "AT_RISK";
  generatedAt: string;
  // NEW: whether budgetAdherence above reflects real user-defined budgets. false means
  // the user hasn't set any budgets yet — the frontend should show something like "Set
  // a budget to include this in your score" rather than the placeholder number, and
  // `score` itself was computed by redistributing that 15% weight across the other
  // three real dimensions rather than trusting a fabricated value.
  budgetAdherenceIsReal: boolean;
}

export interface DashboardSummaryDTO {
  netWorth: string;
  cashBalance: string;
  monthlyIncome: string;
  monthlyExpenses: string;
  savingsRate: number;
  healthScore: FinancialHealthScoreDTO;
  insights: InsightDTO[];
  investmentsValue: string;
  totalDebt: string;
  propertyValue: string;
  unreadAlertCount: number;
  // NEW (audit item #18): cashBalance minus the current-amount of any Goal that isn't
  // backed by a linked Investment — an approximation of cash that's already earmarked
  // toward a savings goal rather than freely available. Deliberately labeled as an
  // approximation (goal.currentAmount is user-entered and may or may not physically sit
  // inside the same cash the app derives cashBalance from) — see emergencyFundBasis for
  // the related, more concrete field.
  uncommittedCash: string;
  // NEW (audit item #2): which data source emergencyFundMonths (in healthScore.breakdown)
  // and emergencyFundAmount below were actually computed from.
  // "GOAL": at least one Goal with type EMERGENCY_FUND exists — the real fix, no longer
  //   coupled to an Expense category literally named "Emergency Fund".
  // "CATEGORY_LEGACY": no EMERGENCY_FUND goal exists yet, so the original category-name
  //   match is used as a fallback for backward compatibility with any account already
  //   relying on that behavior.
  // "NONE": neither a goal nor a matching category expense was found this month.
  // "LEDGER": the EmergencyFundEntry reserve ledger (authoritative once any entry exists).
  emergencyFundBasis: "LEDGER" | "GOAL" | "CATEGORY_LEGACY" | "NONE";
  // The liquid reserve amount emergencyFundMonths (in healthScore.breakdown) was derived
  // from, in the currency's smallest display form (2dp string), regardless of basis.
  emergencyFundAmount: string;
  // NEW (audit item #1): monthlyIncome above has always been recurrence-normalized
  // FORECAST income (IncomeService.monthlyForecast()), not date-filtered actual
  // transactions like Reports' monthlyReport().income uses — this makes that basis
  // explicit rather than only documented in a code comment, so a user comparing the two
  // pages (or the AI Coach explaining the difference) has a concrete field to point to.
  monthlyIncomeBasis: "FORECAST";
  // ACTUAL-basis savings rate for the month (percent, 1 dp, may be NEGATIVE), computed from recorded
  // income and recorded expenses only. null when no income has been recorded this month.
  // `savingsRate` above keeps its legacy meaning (forecast income vs actual expenses, floored at 0)
  // for older clients; `savingsRateBasis` names exactly what it is.
  savingsRateActual?: number | null;
  savingsRateBasis?: "FORECAST_INCOME_VS_ACTUAL_EXPENSES";
  // NEW (financial-core upgrade) — all optional so older clients/fixtures keep working.
  // `cashBalance` above is now exactly `availableCash` (it never included reserved money);
  // the three cash concepts are surfaced explicitly instead of one ambiguous balance.
  availableCash?: string;
  emergencyCash?: string;
  totalCash?: string;
  // ACTUAL contributions to investments this month — never part of monthlyExpenses.
  monthlyInvestmentContributions?: string;
  // Percent (0-100, 1dp) like `savingsRate`, derived from ACTUAL income for the month.
  investmentRate?: number;
  // monthlyExpenses is actual spending only (SIPs / reserve allocations excluded).
  monthlyExpensesBasis?: "ACTUAL";
  // Data-quality warnings from the shared facts layer (legacy SIP/emergency "expenses",
  // stale valuations). Same list the AI Coach consumes.
  dataHealth?: FinancialDataHealthWarningDTO[];
}

export interface FinancialDataHealthWarningDTO {
  code: string;
  severity: "WARNING" | "INFO";
  message: string;
  count: number;
  amount?: string;
}

export interface InsightDTO {
  id: string;
  title: string;
  detail: string;
  severity: "INFO" | "WARNING" | "CRITICAL";
  isProjectionOnly: true;
}

export interface ApiError {
  statusCode: number;
  message: string;
  error?: string;
}

// --- Phase 2: Investments, Loans, Insurance, Goals -------------------------------

export type InvestmentType =
  | "MUTUAL_FUND"
  | "STOCK"
  | "ETF"
  | "EPF"
  | "PPF"
  | "NPS"
  | "FD"
  | "BOND"
  | "GOLD"
  | "SILVER"
  | "REAL_ESTATE"
  | "CRYPTO"
  | "BUSINESS_EQUITY"
  | "OTHER";
export type RiskLevel = "LOW" | "MODERATE" | "HIGH";
export type Liquidity = "LIQUID" | "SEMI_LIQUID" | "ILLIQUID";
export type LoanType =
  | "HOME"
  | "CAR"
  | "EDUCATION"
  | "PERSONAL"
  | "BUSINESS"
  | "CREDIT_CARD"
  | "FAMILY"
  | "OTHER";
export type InsuranceType =
  | "HEALTH"
  | "TERM"
  | "VEHICLE"
  | "HOME"
  | "PERSONAL_ACCIDENT"
  | "CRITICAL_ILLNESS"
  | "TRAVEL"
  | "BUSINESS";
export type GoalType =
  | "EMERGENCY_FUND"
  | "HOUSE"
  | "LAND"
  | "CAR"
  | "MARRIAGE"
  | "CHILD_EDUCATION"
  | "RETIREMENT"
  | "EARLY_RETIREMENT"
  | "BUSINESS_EXPANSION"
  | "VACATION"
  | "HEALTHCARE_RESERVE"
  | "PASSIVE_INCOME"
  | "FAMILY_SUPPORT"
  | "OTHER";

export interface InvestmentDTO {
  id: string;
  userId: string;
  type: InvestmentType;
  name: string;
  currentValue: string;
  costBasis: string;
  purchaseDate: string;
  riskLevel: RiskLevel;
  liquidity: Liquidity;
  goalId: string | null;
  notes: string | null;
  // Recurring-contribution schedule (present on rows from the API; absent when none is set).
  // monthlyContribution is the amount PER PERIOD despite its legacy name.
  monthlyContribution?: string | null;
  contributionDay?: number | null;
  contributionFrequency?: Recurrence;
  contributionStartDate?: string | null;
  contributionEndDate?: string | null;
  sipActive?: boolean;
  // The user's ASSUMED annual return in percent, used only by projections.
  expectedAnnualReturn?: string | null;
}

export interface InvestmentSummaryDTO {
  totalCurrentValue: string;
  totalCostBasis: string;
  totalGainLoss: string;
  totalGainLossPercent: number;
  allocation: { type: InvestmentType; value: number; percent: number }[];
}

// NEW (audit item #11): one row per explicit, user-recorded sale/disposal — created
// only via InvestmentsService.recordSale(), never inferred automatically. See
// capital-gains.util.ts (backend) for what gainCategory values mean.
export interface RealizedGainEventDTO {
  id: string;
  userId: string;
  investmentId: string;
  investmentType: InvestmentType;
  saleDate: string;
  proceeds: string;
  costBasisPortion: string;
  gainAmount: string; // negative means a loss
  holdingPeriodDays: number;
  gainCategory: "EQUITY_SHORT_TERM" | "EQUITY_LONG_TERM" | "CRYPTO" | "OTHER_SHORT_TERM" | "OTHER_LONG_TERM";
  financialYear: string;
  notes: string | null;
  createdAt: string;
}

export type RebalanceActionKind = "BUY" | "SELL" | "HOLD";

export interface RebalanceActionDTO {
  type: InvestmentType;
  currentValue: number;
  currentPercent: number;
  // "What you asked for" — the target implied directly by the input percent against the
  // full totalAfterCash. Unchanged meaning from before this change.
  targetPercent: number;
  targetValue: number;
  // "What's actually achievable" — equal to targetPercent/targetValue when nothing in
  // the plan is constrained. When one or more no-sell types can't reach their target,
  // the shortfall is redistributed proportionally across the remaining types by their
  // relative target weights, and BUY/SELL amounts are computed against these effective
  // values instead of the raw target — see InvestmentsService.resolveConstrainedTargets().
  // For a constrained type itself, these equal currentValue/currentPercent (it's locked).
  effectiveTargetPercent: number;
  effectiveTargetValue: number;
  action: RebalanceActionKind;
  amount: number;
  constrained: boolean;
}

export interface RebalancePlanDTO {
  totalCurrentValue: string;
  cashAvailable: string;
  totalAfterCash: string;
  actions: RebalanceActionDTO[];
  totalBuy: string;
  totalSell: string;
}

export interface LoanDTO {
  id: string;
  userId: string;
  type: LoanType;
  lender: string;
  principal: string;
  outstandingPrincipal: string;
  interestRateAnnual: string;
  tenureMonths: number;
  emiAmount: string;
  startDate: string;
  notes: string | null;
}

export interface DebtSummaryDTO {
  totalOutstanding: string;
  totalMonthlyEmi: string;
  debtStressScore: number; // EMI as % of monthly income
  loans: LoanDTO[];
}

export interface InsurancePolicyDTO {
  id: string;
  userId: string;
  type: InsuranceType;
  provider: string;
  policyNumber: string | null;
  premiumAmount: string;
  premiumFrequency: Recurrence;
  coverageAmount: string;
  renewalDate: string;
  nomineeName: string | null;
  // NEW (audit item #13): optional link to a household Dependent record, alongside
  // (not replacing) nomineeName above — null for every pre-existing policy and for
  // any policy naming a non-household nominee.
  nomineeDependentId: string | null;
  notes: string | null;
}

export interface CoverageGapDTO {
  type: InsuranceType;
  hasCoverage: boolean;
  currentCoverage: string;
  recommendedCoverage: string;
  gap: string;
  message: string;
}

export interface GoalDTO {
  id: string;
  userId: string;
  type: GoalType;
  name: string;
  targetAmount: string;
  targetDate: string;
  currentAmount: string;
  monthlyContribution: string;
  linkedInvestmentValue: string;
  requiredMonthlyContribution: number;
  progressPercent: number;
  probabilityOfSuccess: "ON_TRACK" | "AT_RISK" | "OFF_TRACK";
  // NEW: the honest numeric signal behind probabilityOfSuccess — a real ratio
  // (monthlyContribution / requiredMonthlyContribution), not a bucketed label. 1 means
  // "no further contribution is actually needed." Uncapped above 1.
  contributionPaceRatio: number;
  // NEW: explicit, permanent, machine-readable disclosure that probabilityOfSuccess was
  // never a modeled probability — closes the audit's flagged naming concern
  // ("slightly misleading naming for what is a threshold-based rule, not a stochastic
  // estimate") without a breaking rename of the field 4+ existing consumers already
  // match against by exact string value.
  isPaceHeuristic: true;
  // NEW: the linked investment value projected forward to the target date at
  // assumedAnnualReturnPercent (equal to today's linkedInvestmentValue when that's
  // unset/0%) — the actual input requiredMonthlyContribution and probabilityOfSuccess
  // are now computed against.
  projectedInvestmentValueAtTarget: string;
  // NEW: the assumed annual growth rate actually used above, as a percentage string
  // ("0.00" when unset) — surfaces what assumption produced the projection.
  assumedAnnualReturnPercent: string;
}

// --- Phase 3: Tax, Retirement, Alerts, Settings -----------------------------------

export type TaxSection =
  | "SECTION_80C"
  | "SECTION_80D"
  | "SECTION_80CCD_1B"
  | "HRA"
  | "HOME_LOAN_INTEREST"
  | "SECTION_80TTA"
  | "SECTION_80E"
  | "OTHER";

export type AlertType =
  | "EMI_DUE"
  | "INSURANCE_RENEWAL"
  | "BUDGET_OVERSPEND"
  | "GOAL_DELAY"
  | "SUBSCRIPTION_RENEWAL"
  | "DEBT_STRESS"
  | "DOCUMENT_EXPIRY"
  | "BUSINESS_OBLIGATION_DUE";

export type AlertSeverity = "INFO" | "WARNING" | "CRITICAL";
export type DigestFrequency = "DAILY" | "WEEKLY" | "OFF";
export type Theme = "LIGHT" | "DARK" | "SYSTEM";
export type AppLanguage = "EN" | "HI" | "MR";

export interface TaxDeductionDTO {
  id: string;
  userId: string;
  section: TaxSection;
  description: string;
  amount: string;
  financialYear: string;
}

// NEW (audit item #11): capital gains from explicitly-recorded investment sales for a
// given financial year. See capital-gains.util.ts (backend) for the full LTCG/STCG
// rule documentation this is computed from.
export interface CapitalGainsSummaryDTO {
  financialYear: string;
  equityShortTermGain: string;
  equityLongTermGain: string;
  equityLongTermExemptionUsed: string;
  // Only positive crypto gains — crypto losses cannot offset anything (a real rule,
  // not a simplification) and are tracked separately below instead.
  cryptoGain: string;
  cryptoLossDisallowed: string;
  otherShortTermGain: string;
  otherLongTermGain: string;
  equityShortTermTax: string;
  equityLongTermTax: string;
  cryptoTax: string;
  // Computed at the marginal slab rate (added to the old regime's taxable income) —
  // see TaxService.capitalGainsSummary()'s own doc comment for the disclosed
  // old-regime-only simplification.
  otherShortTermTax: string;
  otherLongTermTax: string;
  totalCapitalGainsTax: string;
  isProjectionOnly: true;
}

export interface TaxEstimateDTO {
  financialYear: string;
  grossAnnualIncome: string;
  totalDeductions: string;
  // `surcharge` is new on both regime objects — the surcharge amount actually applied
  // (in rupees, already included in taxPayable), so the UI can show it as its own line
  // item. Zero for any income below the ₹50L threshold, matching every existing case.
  // `marginalReliefApplied` (audit item #14): true when the surcharge above was
  // reduced by marginal relief — the provision that caps how much crossing a
  // surcharge threshold can increase total tax, so earning ₹1 over a threshold never
  // costs thousands more than earning exactly the threshold amount. false for every
  // income that doesn't cross a threshold closely enough for relief to matter
  // (including every income below ₹50L, matching every existing case).
  oldRegime: { taxableIncome: string; taxPayable: string; surcharge: string; marginalReliefApplied: boolean };
  newRegime: { taxableIncome: string; taxPayable: string; surcharge: string; marginalReliefApplied: boolean };
  recommendedRegime: "OLD" | "NEW";
  savingsFromRecommendedRegime: string;
  deductionsBySection: { section: TaxSection; used: string; limit: string; remainingRoom: string }[];
  yearEndChecklist: string[];
  // NEW (audit item #11): a separate line item, not folded into oldRegime/
  // newRegime.taxPayable above — most capital gains (equity/crypto/other-LTCG) are
  // taxed at flat rates that don't depend on the chosen regime. Add
  // capitalGains.totalCapitalGainsTax to whichever regime's taxPayable you're
  // comparing to get that regime's full liability.
  capitalGains: CapitalGainsSummaryDTO;
  isProjectionOnly: true;
  // NEW: which financial year's slab configuration was actually used to compute this
  // estimate, and whether it had to be approximated from the latest available year
  // because the requested financialYear isn't in tax-slab-config.ts yet (e.g. a future
  // Budget hasn't been added). Lets the frontend show "using FY2025-26 rates as an
  // estimate" instead of silently presenting potentially-stale slabs with false
  // precision — this is the actual transparency mechanism behind the versioned-config
  // fix, not just an internal implementation detail.
  slabsFinancialYear: string;
  slabsAreEstimated: boolean;
}

export interface RetirementProfileDTO {
  targetRetirementAge: number;
  desiredMonthlyIncomeToday: string;
  inflationRatePercent: string;
  expectedReturnPreRetirementPercent: string;
  expectedReturnPostRetirementPercent: string;
}

export interface RetirementPlanDTO {
  yearsToRetirement: number;
  monthlyIncomeAtRetirement: string;
  corpusRequired: string;
  currentRetirementCorpus: string;
  corpusGap: string;
  requiredMonthlySip: string;
  onTrack: boolean;
  isProjectionOnly: true;
  // NEW: the actual post-retirement drawdown horizon used in corpusRequired's PV
  // calculation — either derived from the profile's lifeExpectancyAge, or the
  // long-standing 25-year default when that field is unset (or not later than
  // targetRetirementAge). isHorizonFromLifeExpectancy tells the frontend which case
  // applied, so it can label the figure accordingly ("based on your life expectancy"
  // vs. "using a standard 25-year assumption").
  drawdownHorizonYears: number;
  isHorizonFromLifeExpectancy: boolean;
  // NEW: how much of monthlyIncomeAtRetirement is expected to be covered by a
  // guaranteed pension/annuity (expectedMonthlyPensionAtRetirement on the profile) —
  // "0.00" when unset, matching the original all-corpus-funded assumption.
  monthlyPensionOffset: string;
  // NEW: monthlyIncomeAtRetirement minus monthlyPensionOffset — the portion that
  // actually has to be funded from the investment corpus, and the true input to
  // corpusRequired's calculation. Equal to monthlyIncomeAtRetirement whenever no
  // pension is assumed.
  netMonthlyIncomeNeededFromCorpus: string;
}

export interface AlertDTO {
  id: string;
  userId: string;
  type: AlertType;
  severity: AlertSeverity;
  title: string;
  message: string;
  dueDate: string | null;
  isRead: boolean;
  createdAt: string;
}

export interface UserSettingsDTO {
  notifyEmail: boolean;
  digestFrequency: DigestFrequency;
  theme: Theme;
  language: AppLanguage;
}

// --- Phase 4: Property, Business Tracker, Document Vault, Reports ----------------

export type PropertyType = "HOUSE" | "APARTMENT" | "PLOT" | "LAND" | "COMMERCIAL" | "RENTAL";

export interface PropertyDTO {
  id: string;
  userId: string;
  type: PropertyType;
  name: string;
  address: string | null;
  currentValue: string;
  purchasePrice: string;
  purchaseDate: string;
  isRented: boolean;
  monthlyRentalIncome: string | null;
  annualMaintenanceCost: string;
  annualPropertyTax: string;
  loanId: string | null;
  insurancePolicyId: string | null;
  // NEW (audit item #10): set once PropertyService.enableRentIncomeSync() has been
  // called — the id of the recurring Income row this property's rent is synced to,
  // or null if not synced (the default, and every pre-existing property's state).
  rentSyncedIncomeId: string | null;
  notes: string | null;
}

export interface PropertyMetricsDTO {
  currentValue: string;
  purchasePrice: string;
  appreciationPercent: number;
  linkedLoanOutstanding: string | null;
  equity: string;
  rentalYieldPercent: number | null;
  netAnnualCarryCost: string; // maintenance + property tax − annual rental income
}

export interface PropertyPortfolioSummaryDTO {
  totalCurrentValue: string;
  totalEquity: string;
  properties: (PropertyDTO & { metrics: PropertyMetricsDTO })[];
}

export type BusinessTransactionType = "REVENUE" | "EXPENSE" | "OWNER_DRAWING";
export type BusinessEntityType = "SOLE_PROPRIETORSHIP" | "PARTNERSHIP" | "LLP" | "PRIVATE_LIMITED" | "OTHER";
export type ObligationStatus = "PENDING" | "PAID" | "OVERDUE" | "CANCELLED";

export interface BusinessDTO {
  id: string;
  userId: string;
  name: string;
  description: string | null;
  entityType: BusinessEntityType;
  currency: string;
  startedAt: string | null;
  ownershipPercent: string | null;
}

export interface BusinessTransactionDTO {
  id: string;
  businessId: string;
  type: BusinessTransactionType;
  category: string | null;
  amount: string;
  occurredAt: string;
  description: string | null;
  isRecurring: boolean;
  // NEW (audit item #9): set once BusinessService.syncDrawingToIncome() has been
  // called on this (OWNER_DRAWING) transaction — the id of the personal Income row
  // it's synced to, or null (the default, and every non-drawing transaction's state).
  syncedIncomeId: string | null;
}

export interface BusinessObligationDTO {
  id: string;
  businessId: string;
  title: string;
  dueDate: string;
  amount: string | null;
  recurrence: Recurrence;
  vendor: string | null;
  status: ObligationStatus;
  notes: string | null;
}

export interface BusinessSummaryDTO {
  businessId: string;
  month: string; // "YYYY-MM"
  revenue: string;
  expenses: string;
  ownerDrawings: string;
  profit: string;
  trend: { month: string; revenue: number; expenses: number; profit: number }[];
}

export type DocumentCategory =
  | "PAN"
  | "AADHAAR"
  | "SALARY_SLIP"
  | "FORM_16"
  | "INSURANCE_POLICY"
  | "LOAN_DOCUMENT"
  | "MF_STATEMENT"
  | "TAX_RETURN"
  | "PROPERTY_PAPER"
  | "BUSINESS_DOCUMENT"
  | "RECEIPT"
  | "BILL"
  | "OTHER"
  // NEW (audit item #6): routing target for the Document -> Copilot Ingestion bridge.
  | "BANK_STATEMENT";

export type OcrStatus = "NOT_APPLICABLE" | "PENDING" | "DONE" | "FAILED";

export interface DocumentDTO {
  id: string;
  userId: string;
  category: DocumentCategory;
  fileName: string;
  mimeType: string;
  sizeBytes: number;
  tags: string[];
  expiryDate: string | null;
  ocrStatus: OcrStatus;
  ocrText: string | null;
  summary: string | null;
  // NEW (document entity linking) — optional so older fixtures keep compiling.
  entityType?: DocumentEntityType | null;
  entityId?: string | null;
  documentType?: string | null;
  extractionConfidence?: string | null;
  createdAt: string;
}

export type DocumentEntityType = "POLICY" | "INVESTMENT" | "LOAN" | "PROPERTY" | "INCOME" | "TAX" | "BUSINESS";

export interface DocumentDiscrepancyDTO {
  id: string;
  documentId: string;
  entityType: DocumentEntityType;
  entityId: string;
  field: string;
  documentValue: string;
  databaseValue: string;
  status: "OPEN" | "KEPT_DATABASE" | "DISMISSED" | "RESOLVED";
  createdAt: string;
  resolvedAt: string | null;
}

export interface MonthlyReportDTO {
  month: string;
  income: string;
  expenses: string;
  netCashflow: string;
  savingsRate: number;
  expensesByCategory: { category: string; amount: string; percentOfTotal: number }[];
  // NEW (audit item #1): Reports has always computed both figures from actual,
  // date-filtered transactions — this makes that basis explicit and machine-readable
  // rather than only documented in a code comment, and lets the frontend/AI Coach
  // explain to a user why this figure can differ from Dashboard's forecast-based
  // monthlyIncome for the same month.
  incomeBasis: "ACTUAL";
  expensesBasis: "ACTUAL";
}

export interface YearlyReportDTO {
  financialYear: string;
  totalIncome: string;
  totalExpenses: string;
  netSavings: string;
  investmentsCurrentValue: string;
  totalDebtOutstanding: string;
  businessProfit: string | null;
  expensesByCategory: { category: string; amount: string; percentOfTotal: number }[];
}

// --- FinancialFactsService (audit item #1) ----------------------------------------
// A canonical, explicitly-basis-labeled way to ask "what's this user's monthly income"
// (etc.) that Dashboard, Reports, Tax, Retirement, Simulator, and the Coach can all
// consume instead of each independently re-deriving the same figure with a different,
// undocumented basis. See FinancialFactsService for the actual computation.

// ACTUAL = recorded history; FORECAST = normalized recurring expectation; PROJECTED =
// scenario/what-if output; TARGET = a goal/threshold the user set; ESTIMATED = derived
// from incomplete data. A forecast must never silently be presented as an actual.
export type FinancialFactBasis = "ACTUAL" | "FORECAST" | "PROJECTED" | "TARGET" | "ESTIMATED";
export type FinancialFactPeriod = "MONTHLY" | "YEARLY" | "LIFETIME" | "CUSTOM";
export type FinancialFactConfidence = "HIGH" | "MEDIUM" | "LOW";

export interface FinancialFactDTO {
  metric: string;
  value: string;
  currency: string;
  basis: FinancialFactBasis;
  asOf: string;
  sourceTypes: string[];
  confidence: FinancialFactConfidence;
  explanationKey: string;
}

// --- Phase 5: AI Coach, What-If Simulator, Household views -----------------------

export interface CoachInteractionDTO {
  id: string;
  question: string;
  answer: string;
  matchedIntent: string | null;
  dataSources: string[];
  wasRefused: boolean;
  createdAt: string;
}

export type ScenarioType =
  | "SALARY_HIKE"
  | "SALARY_DROP"
  | "SIP_INCREASE"
  | "SIP_DECREASE"
  | "HOUSE_PURCHASE"
  | "LOAN_PREPAYMENT"
  | "RETIREMENT_AGE_SHIFT"
  | "EMERGENCY_EXPENSE"
  | "GOAL_DELAY"
  // NEW (audit item #8): a new/expansion loan not tied to purchasing a house — personal
  // loan, business expansion, equipment financing, etc. Previously such prompts had no
  // matching type and were forced into LOAN_PREPAYMENT or HOUSE_PURCHASE.
  | "NEW_LOAN";

export interface ScenarioParamsByType {
  SALARY_HIKE: { percentIncrease: number };
  SALARY_DROP: { percentDecrease: number };
  SIP_INCREASE: { additionalMonthlyAmount: number };
  SIP_DECREASE: { reducedMonthlyAmount: number };
  HOUSE_PURCHASE: { propertyValue: number; downPaymentPercent: number; loanInterestRateAnnual: number; loanTenureMonths: number };
  LOAN_PREPAYMENT: { loanId: string; lumpSum: number };
  RETIREMENT_AGE_SHIFT: { newRetirementAge: number };
  EMERGENCY_EXPENSE: { amount: number };
  GOAL_DELAY: { goalId: string; delayMonths: number };
  // `purpose` is optional, free-text, and purely for the narrative — never validated or
  // used in the numeric projection (see SimulatorService's REQUIRED_FIELDS, which only
  // requires loanAmount/annualRatePercent/tenureMonths).
  NEW_LOAN: { loanAmount: number; annualRatePercent: number; tenureMonths: number; purpose?: string };
}

// Per-loan snapshot (real rate + EMI, not just the aggregate outstanding figure) so the
// Simulator's projection engine can amortize each loan month-by-month during the
// projection window instead of holding total debt flat. Numeric (not string/Decimal)
// since this feeds directly into the pure engine's arithmetic, not display formatting.
export interface ScenarioLoanSnapshotDTO {
  id: string;
  principal: number; // current outstanding principal
  annualRatePercent: number;
  emi: number;
}

export interface ScenarioBaselineDTO {
  monthlyIncome: number;
  monthlyExpenses: number;
  netWorth: number;
  investmentsValue: number;
  totalDebt: number;
  currentAge: number | null;
  targetRetirementAge: number;
  // Optional so existing/legacy baseline literals (tests, other in-repo constructors)
  // remain valid without updating every call site — the engine treats a missing/empty
  // array as "no loan-level detail available" and falls back to holding `totalDebt`
  // flat, exactly as before this field existed.
  loans?: ScenarioLoanSnapshotDTO[];
  totalMonthlyEmi?: number;
}

export interface ScenarioResultDTO {
  scenarioType: ScenarioType;
  monthlyCashflowDelta: string;
  netWorthDeltaIn5Years: string;
  projectedNetWorthIn5Years: string;
  goalImpact: string;
  assumptions: string[];
  narrative: string;
  isProjectionOnly: true;
}

export interface RunScenarioResponseDTO {
  baseline: ScenarioBaselineDTO;
  result: ScenarioResultDTO;
}

export interface SavedScenarioDTO {
  id: string;
  scenarioType: ScenarioType;
  label: string;
  params: Record<string, unknown>;
  result: ScenarioResultDTO;
  createdAt: string;
}

export interface HouseholdMemberSummaryDTO {
  userId: string;
  name: string | null;
  role: Role;
  monthlyIncome: string;
  monthlyExpenses: string;
  netWorth: string;
  investmentsValue: string;
  propertyValue: string;
  totalDebt: string;
  goalCount: number;
  unreadAlertCount: number;
}

export interface SharedSubscriptionFlagDTO {
  merchant: string;
  memberNames: (string | null)[];
}

export interface HouseholdSummaryDTO {
  householdId: string;
  householdName: string;
  memberCount: number;
  totalMonthlyIncome: string;
  totalMonthlyExpenses: string;
  totalNetWorth: string;
  totalInvestments: string;
  totalDebt: string;
  totalPropertyValue: string;
  totalGoalsTarget: string;
  totalGoalsSaved: string;
  totalBusinessProfitThisMonth: string;
  totalUnreadAlerts: number;
  // Merchants detected as recurring for 2+ different members — flagged rather than
  // merged, since we can't tell from the data alone whether it's genuinely one shared
  // subscription split between people or two separate individual ones.
  possibleSharedSubscriptions: SharedSubscriptionFlagDTO[];
  viewerRole: Role;
  // Per-member breakdown is only populated for OWNER viewers — MEMBER viewers get
  // aggregate totals only, never other members' individual figures. Even for OWNER,
  // this is dashboard-level aggregate detail per member, never raw transaction rows.
  members: HouseholdMemberSummaryDTO[] | null;
}

// --- Phase 10: AI Gateway ops -----------------------------------------------------
// No product-facing page consumes these yet (Phase 10 is infrastructure, not a user
// feature) — they're here so the eventual ops dashboard / RAG / Coach 2.0 frontend
// work in later phases has a shared shape to import from day one rather than
// duplicating it, matching how every other DTO in this file is used.

export interface AiHealthStatsDTO {
  windowMinutes: number;
  totalCalls: number;
  errorCount: number;
  errorRate: number | null;
  cacheHitRate: number | null;
  avgLatencyMs: number | null;
}

export interface AiHealthDTO {
  groqConfigured: boolean;
  lastHourStats: AiHealthStatsDTO;
  queue: Record<string, number>;
  checkedAt: string;
}

export type AiJobStatus = "QUEUED" | "RUNNING" | "DONE" | "FAILED";

export interface AiJobStatusDTO {
  id: string;
  type: string;
  status: AiJobStatus;
  result: Record<string, unknown> | null;
  error: string | null;
  createdAt: string;
  updatedAt: string;
}

// --- Phase 11: RAG engine ----------------------------------------------------------

export type AiSourceType = "DOCUMENT" | "REPORT" | "COACH_INTERACTION" | "ALERT" | "SNAPSHOT" | "FINANCIAL_FACT";

export interface AiCitedSourceDTO {
  chunkId: string;
  sourceType: AiSourceType;
  sourceId: string;
  title: string;
  snippet: string;
  score: number;
}

export interface AiSearchFiltersDTO {
  sourceTypes?: AiSourceType[];
  dateFrom?: string;
  dateTo?: string;
}

export interface AiSearchResultDTO {
  query: string;
  rewrittenQueries: string[];
  isMultiHop: boolean;
  subQuestions: string[];
  hasEvidence: boolean;
  answer: string;
  citedSources: AiCitedSourceDTO[];
  retrievalConfidence: number;
  answerConfidence: number | null;
  explanation: string;
}

export interface AiSearchLogDTO {
  id: string;
  query: string;
  answer: string;
  hadEvidence: boolean;
  retrievalConfidence: string;
  answerConfidence: string | null;
  createdAt: string;
}

// --- Phase 12: Agentic Coach --------------------------------------------------------

export type CoachPath = "DETERMINISTIC" | "ADVANCED";

export type AdvancedCoachIntent =
  | "prioritize_actions"
  | "goal_conflict"
  | "risk_tradeoff"
  | "compare_periods"
  | "general_search";

export interface AgenticCoachResultDTO {
  question: string;
  path: CoachPath;
  matchedIntent: string | null;
  advancedIntent: AdvancedCoachIntent | null;
  plan: string[];
  facts: Record<string, unknown>;
  citedSources: string[];
  answer: string;
  confidence: number;
  verificationPassed: boolean;
  staleAdviceNote: string | null;
  planId: string | null;
  criticFlags: string[];
  createdTaskIds: string[];
}

export interface AgenticCoachRunDTO {
  id: string;
  question: string;
  path: CoachPath;
  matchedIntent: string | null;
  advancedIntent: AdvancedCoachIntent | null;
  plan: string[];
  facts: Record<string, unknown>;
  citedSources: string[];
  answer: string;
  confidence: string;
  verificationPassed: boolean;
  staleAdviceNote: string | null;
  createdAt: string;
}

// --- Phase 13: Scenario Studio ------------------------------------------------------

export type ScenarioVariantLabel = "best" | "base" | "worst" | "constrained";

export interface ScenarioVariantDTO {
  label: ScenarioVariantLabel;
  params: Record<string, unknown>;
  run: RunScenarioResponseDTO;
  feasible: boolean;
  feasibilityNote: string;
}

export interface SensitivityPointDTO {
  paramValue: number;
  projectedNetWorthIn5Years: number;
  netWorthDeltaIn5Years: number;
}

export interface SensitivityDimensionDTO {
  dimension: string;
  field: string;
  points: SensitivityPointDTO[];
}

export interface GoalImpactNoteDTO {
  goalId: string;
  goalName: string;
  requiredMonthlyContribution: number;
  helped: boolean;
  note: string;
}

export interface RankedVariantDTO {
  label: ScenarioVariantLabel;
  score: number;
  netWorthDeltaIn5Years: number;
  feasible: boolean;
  feasibilityNote: string;
  goalImpacts: GoalImpactNoteDTO[];
}

export interface ScenarioStudioResultDTO {
  prompt: string;
  understood: boolean;
  scenarioType: ScenarioType | null;
  baseParams: Record<string, unknown>;
  variants: ScenarioVariantDTO[];
  sensitivity: SensitivityDimensionDTO[];
  ranked: RankedVariantDTO[];
  explanation: string;
  explanationConfidence: number;
  verificationPassed: boolean;
  // Fast, reduced-fidelity Monte Carlo preview of the ranked winner's parameters —
  // null when the preview itself failed (e.g. AI/DB hiccup) or was skipped; never
  // blocks the rest of the (already-deterministic) result from being returned. See
  // ScenarioStudioService.build() and BUILD_MC_PREVIEW_ITERATIONS.
  monteCarloSummary: MonteCarloResultDTO | null;
}

export interface ScenarioStudioRunDTO {
  id: string;
  prompt: string;
  scenarioType: string;
  baseParams: Record<string, unknown>;
  targetGoalIds: string[];
  variants: Record<string, unknown>[];
  sensitivity: SensitivityDimensionDTO[];
  rankedOrder: ScenarioVariantLabel[];
  explanation: string;
  explanationConfidence: string;
  verificationPassed: boolean;
  monteCarloSummary: MonteCarloResultDTO | null;
  createdAt: string;
}

// --- Phase 14: ML Insights -----------------------------------------------------------

export interface ContributingFeatureDTO {
  name: string;
  value: number;
  contribution: number;
}

export interface ModelOutputDTO<T> {
  method: string;
  prediction: T;
  confidence: number;
  contributingFeatures: ContributingFeatureDTO[];
  explanation: string;
}

export interface ExpenseAnomalyDTO {
  transactionId: string;
  categoryName: string;
  amount: number;
  categoryMedian: number;
  zScore: number;
  /** NEW — deterministic, rule-based candidate reasons this transaction was flagged
   * (new merchant, first-in-category, recurring-amount change, magnitude vs. median).
   * Always present and always traceable to the input data, independent of whether the
   * LLM narrative below (see MlInsightsSummaryDTO.anomalyExplanation) was available. */
  likelyCauses: string[];
}

/** NEW — result of the AI-Gateway-backed anomaly explanation call. `usedFallback`
 * true means `narrative` is the deterministic, rule-based fallback (built directly
 * from ExpenseAnomalyDTO.likelyCauses) rather than an LLM composition — surfaced
 * explicitly so the UI can show "AI explanation unavailable" without guessing from
 * confidence alone. */
export interface AnomalyExplanationDTO {
  narrative: string;
  confidence: number;
  verificationPassed: boolean;
  usedFallback: boolean;
}

export interface QuantileForecastPointDTO {
  monthsAhead: number;
  p10: number;
  p50: number;
  p90: number;
}

export interface CashflowForecastDTO {
  nextMonthProjectedCashflow: number;
  trendSlopePerMonth: number;
  stressRisk: boolean;
  /** NEW — 95% confidence interval around nextMonthProjectedCashflow. */
  confidenceInterval95: { lower: number; upper: number };
  /** NEW — P10/P50/P90 projected net cashflow, 1/2/3 months ahead. */
  quantileForecast: QuantileForecastPointDTO[];
  /** NEW — trend/seasonal/residual decomposition summary of the historical series.
   * hasSeasonality is false (and seasonalAdjustmentThisMonth is 0) unless there are
   * 24+ months of history — with less, a per-calendar-month seasonal index would be
   * statistically indistinguishable from noise. */
  decomposition: { hasSeasonality: boolean; seasonalAdjustmentThisMonth: number; residualStdDev: number };
  /** NEW — this user's own long-run mean/stdDev net cashflow, the Bayesian prior
   * behind the forecast above ("personalized baseline"). */
  personalizedBaseline: { historicalMean: number; historicalStdDev: number };
}

export type ForecastMetricNameDTO = "income" | "expenses" | "savingsRate";

export interface MetricForecastResultDTO {
  metric: ForecastMetricNameDTO;
  nextMonthP50: number;
  trendSlopePerMonth: number;
  confidenceInterval95: { lower: number; upper: number };
  quantileForecast: QuantileForecastPointDTO[];
  decomposition: { hasSeasonality: boolean; trendSlope: number };
  personalizedBaseline: { historicalMean: number; historicalStdDev: number };
  fitQuality: number;
}

/** NEW — independent Bayesian quantile forecasts for income, expenses, and savings
 * rate (distinct from CashflowForecastDTO, which forecasts only the combined net
 * cashflow figure). */
export interface MetricsForecastDTO {
  income: MetricForecastResultDTO;
  expenses: MetricForecastResultDTO;
  savingsRate: MetricForecastResultDTO;
  insufficientHistory: boolean;
}

export interface DebtRiskPredictionDTO {
  riskScore: number;
  tier: "low" | "moderate" | "high" | "severe";
}

export interface GoalSuccessPredictionDTO {
  goalId: string;
  goalName: string;
  successProbability: number;
  // NEW: GoalsService's own threshold-based tier, carried through unchanged so a
  // consumer can display both the statistical read and the rule-based read together
  // instead of the two disagreeing silently across different screens.
  ruleBasedTier: "ON_TRACK" | "AT_RISK" | "OFF_TRACK";
  // NEW: explicit, precomputed agreement flag between successProbability (>=50%) and
  // ruleBasedTier (ON_TRACK/AT_RISK read as "on pace", OFF_TRACK as "not") — lets the
  // UI flag a disagreement without re-deriving the comparison itself.
  agreesWithRuleBasedTier: boolean;
}

export interface DriftPredictionDTO {
  drifted: boolean;
  direction: "improving" | "worsening" | "none";
  recentWindowMeanSavingsRate: number;
  priorWindowMeanSavingsRate: number;
  zStatistic: number;
}

/** NEW — model-performance monitoring: has the cashflow FORECAST MODEL's own
 * prediction error gotten worse over time. Distinct from DriftPredictionDTO, which
 * tracks whether the USER's savings rate itself has shifted. `monitored: false` means
 * there isn't yet enough resolved forecast history (predicted-then-realized months)
 * to say anything, as opposed to `driftDetected: false` which means "monitored, and
 * stable". */
export interface ConceptDriftPredictionDTO {
  monitored: boolean;
  driftDetected: boolean;
  recentMeanAbsoluteError: number;
  priorMeanAbsoluteError: number;
  sampleSize: number;
  zStatistic: number;
  direction: "degrading" | "improving" | "stable";
}

export interface FeatureShiftResultDTO {
  name: string;
  psi: number;
  severity: "none" | "moderate" | "significant";
}

/** NEW — online feature-distribution-shift monitoring via Population Stability Index
 * between a reference window and the recent window, per engineered feature (avg
 * transaction amount, transactions/month, distinct categories/month). */
export interface FeatureMonitoringPredictionDTO {
  monitored: boolean;
  features: FeatureShiftResultDTO[];
  anyShiftDetected: boolean;
}

export type BehavioralStateDTO = "high_saving" | "balanced" | "overspending";

export interface MonthSegmentDTO {
  month: string;
  savingsRate: number;
  zScoreVsOwnHistory: number;
  state: BehavioralStateDTO;
}

export type SpendingClusterDTO = "disciplined_saver" | "steady_balanced" | "volatile_spender" | "concentrated_spender" | "overspender";

export interface BehavioralFeatureVectorDTO {
  avgSavingsRate: number;
  expenseVolatilityCV: number;
  recurringSpendShare: number;
  categoryConcentrationHHI: number;
  topCategoryName: string | null;
  topCategoryShare: number;
}

/** NEW — user-specific engineered behavioral features (savings-rate level, expense
 * volatility, category concentration, recurring-spend share) plus a rule-based
 * spending-cluster label. */
export interface BehavioralFeatureResultDTO {
  features: BehavioralFeatureVectorDTO;
  cluster: SpendingClusterDTO;
}

export interface MlInsightsSummaryDTO {
  anomalies: ModelOutputDTO<ExpenseAnomalyDTO[]>;
  anomalyExplanation: AnomalyExplanationDTO;
  cashflowForecast: ModelOutputDTO<CashflowForecastDTO>;
  metricsForecast: ModelOutputDTO<MetricsForecastDTO>;
  debtRisk: ModelOutputDTO<DebtRiskPredictionDTO>;
  goalSuccess: ModelOutputDTO<GoalSuccessPredictionDTO[]>;
  drift: ModelOutputDTO<DriftPredictionDTO>;
  conceptDrift: ModelOutputDTO<ConceptDriftPredictionDTO>;
  featureMonitoring: ModelOutputDTO<FeatureMonitoringPredictionDTO>;
  habitSegmentation: ModelOutputDTO<MonthSegmentDTO[]>;
  behavioralFeatures: ModelOutputDTO<BehavioralFeatureResultDTO>;
}

// --- Phase 15: Copilot Ingestion -----------------------------------------------------

export type IngestionItemStatus = "PENDING" | "APPROVED" | "REJECTED";
export type DuplicateResolution = "kept_both" | "skipped_duplicate" | "merged";

export interface IngestionReviewItemDTO {
  id: string;
  batchId: string;
  rawLine: string;
  parsedDate: string;
  parsedAmount: string;
  merchantRaw: string;
  merchantNormalized: string;
  suggestedCategoryId: string | null;
  suggestedCategoryName: string | null;
  categorySuggestionConfidence: string;
  isDuplicateCandidate: boolean;
  duplicateOfExpenseId: string | null;
  duplicateConfidence: string;
  isRecurringCandidate: boolean;
  recurringMatchMerchant: string | null;
  isAnomalyCandidate: boolean;
  anomalyZScore: string | null;
  missingFields: string[];
  overallConfidence: string;
  rationale: string;
  status: IngestionItemStatus;
  resolvedExpenseId: string | null;
  duplicateResolution: string | null;
  createdAt: string;
  resolvedAt: string | null;
}

export type IngestionSourceType = "TEXT" | "OCR_IMAGE" | "DOCUMENT_OCR";

export interface IngestionBatchDTO {
  id: string;
  sourceLabel: string;
  rawTextExcerpt: string;
  totalLines: number;
  parsedCount: number;
  unparsedCount: number;
  items: IngestionReviewItemDTO[];
  createdAt: string;
  // Below were already present on the actual API response (the service returns the
  // raw Prisma row) but missing from this type — added now alongside the genuinely
  // new sourceDocumentId field for a type that actually matches the wire shape.
  ingestionSource: IngestionSourceType;
  ocrExtractionConfidence: string | null;
  // NEW (audit item #6): set only for a batch created automatically via the
  // Document -> Copilot Ingestion bridge (ingestionSource: "DOCUMENT_OCR") — the id
  // of the Document this batch's text was extracted from. Null for every batch
  // created via a pasted-text import or a direct statement-image upload.
  sourceDocumentId: string | null;
}

export interface IngestionBatchSummaryDTO {
  id: string;
  sourceLabel: string;
  totalLines: number;
  parsedCount: number;
  unparsedCount: number;
  createdAt: string;
  _count: { items: number };
}

export interface ApproveReviewItemInput {
  categoryId?: string;
  amount?: number;
  merchant?: string;
  paymentMethod?: string;
  spentAt?: string;
  notes?: string;
  duplicateResolution?: DuplicateResolution;
}
// --- Phase 16: Scenario Studio — Probabilistic Planning (Monte Carlo + Optimization) --
//
// Additive to Phase 13's deterministic Scenario Studio types above — every DTO there
// is unchanged (except ScenarioStudioResultDTO/ScenarioStudioRunDTO gaining one new
// optional-in-spirit `monteCarloSummary` field). The deterministic simulator engine
// (simulator.engine.ts) remains the audited, tested foundation these probabilistic
// features are layered on top of, not a replacement for it.

export interface PercentileSetDTO {
  p10: number;
  p25: number;
  p50: number;
  p75: number;
  p90: number;
}

// A percentile band at one point in time along the projection horizon — the data
// shape a "fan chart" (uncertainty cone) visualization consumes directly.
export interface YearlyBandDTO extends PercentileSetDTO {
  monthIndex: number; // 1-based month within the horizon
}

export type MonteCarloRiskLevel = "LOW" | "MEDIUM" | "HIGH";

export interface MonteCarloConfigDTO {
  iterations: number;
  horizonYears: number;
  seed: number;
  annualReturnMeanPercent: number;
  annualReturnStdDevPercent: number;
  expenseInflationMeanPercent: number;
  expenseInflationStdDevPercent: number;
  incomeGrowthMeanPercent: number;
  incomeGrowthStdDevPercent: number;
  propertyAppreciationMeanPercent: number;
  propertyAppreciationStdDevPercent: number;
}

export interface MonteCarloResultDTO {
  scenarioType: ScenarioType;
  iterations: number;
  horizonYears: number;
  terminalPercentiles: PercentileSetDTO;
  // Fraction (0-1) of simulated trajectories ending below today's actual net worth.
  probabilityOfNetWorthDecline: number;
  // Fraction (0-1) of simulated trajectories ending below a supplied goal target, or
  // null when no target was supplied for this run (not "0% risk" — "not measured",
  // same null-vs-zero distinction AiResult.groundingScore already makes elsewhere).
  probabilityOfGoalShortfall: number | null;
  riskLevel: MonteCarloRiskLevel;
  // stdDev / |mean| of the terminal net worth distribution — the raw number
  // riskLevel is bucketed from, exposed for callers that want finer-grained display.
  coefficientOfVariation: number;
  yearlyBands: YearlyBandDTO[];
  // Human-readable statement of every distributional assumption used, so a UI or an
  // LLM explanation can ground claims in exactly what was modeled rather than an
  // opaque number.
  assumptions: string[];
  config: MonteCarloConfigDTO;
}

// Only scenario types with a single, meaningfully-optimizable decision variable
// support optimization — see OPTIMIZABLE_SCENARIO_TYPES in
// apps/api/src/ai/scenario-studio/scenario-studio.constants.ts for exactly which ones
// and why (e.g. HOUSE_PURCHASE's four interacting fields are explicitly out of scope
// for a single-variable grid search).
export interface OptimizationConstraintsDTO {
  scenarioType: ScenarioType;
  loanId?: string; // required for LOAN_PREPAYMENT
  goalId?: string; // required for GOAL_DELAY
  maxMonthlyBudgetPercent?: number;
  minRetirementAge?: number;
  maxRetirementAge?: number;
  respectGoalFunding?: boolean;
  respectTaxAdvantagedLimit?: boolean;
  targetGoalIds?: string[];
}

export interface OptimizationSearchRangeDTO {
  min: number;
  max: number;
}

export interface OptimizedScenarioDTO {
  scenarioType: ScenarioType;
  recommendedParams: Record<string, unknown>;
  searchRange: OptimizationSearchRangeDTO;
  candidatesEvaluated: number;
  // Full-fidelity Monte Carlo result for the recommended parameters (never a
  // search-time reduced-iteration approximation — see ScenarioOptimizerService).
  monteCarlo: MonteCarloResultDTO;
  feasible: boolean;
  violatedConstraints: string[];
  riskAdjustedScore: number;
  constraintsApplied: OptimizationConstraintsDTO;
}

// NEW (audit item #16): shared shape for the previously backend-only, opt-in
// listPaged() endpoints (Income/Expenses/Investments) — "paginated variants exist as
// opt-in, additive methods only, not the default the UI actually calls." This type
// lets the frontend api client and page components share one definition instead of
// each inlining an ad-hoc paged-response shape.
export interface PagedResult<T> {
  items: T[];
  total: number;
  page: number;
  pageSize: number;
  totalPages: number;
}


// NEW (financial-core upgrade): GET /financial-core/data-health
export interface DataHealthIssueDTO {
  code: string;
  severity: "WARNING" | "INFO";
  message: string;
  count: number;
  amount?: string;
  entityIds: string[];
}

export interface DataHealthReportDTO {
  basis: "ACTUAL";
  asOfDate: string;
  status: "HEALTHY" | "NEEDS_REVIEW";
  issues: DataHealthIssueDTO[];
  checks: Array<{ label: string; ok: boolean }>;
  notChecked: string[];
}

// --- Money flow: receivables (money given) & internal transfers -------------------------------
// A receivable is money handed to someone that is expected BACK. It is never an expense:
// cash falls, a receivable asset rises, net worth and spending are unchanged. returned /
// outstanding are always derived from the repayment ledger.

export type ReceivableStatus = "OUTSTANDING" | "PARTIALLY_RETURNED" | "FULLY_RETURNED" | "OVERDUE" | "CANCELLED";

export interface ReceivableRepaymentDTO {
  id: string;
  receivableId: string;
  amount: string;
  returnedAt: string;
  paymentMethod: PaymentMethod;
  notes: string | null;
  createdAt: string;
}

export interface ReceivableDTO {
  id: string;
  person: string;
  purpose: string | null;
  originalAmount: string;
  returnedAmount: string;
  outstandingAmount: string;
  currency: string;
  givenAt: string;
  expectedReturnAt: string | null;
  // Stored status vs. read-time status: effectiveStatus upgrades an open, past-due
  // receivable to OVERDUE. Render effectiveStatus; use status only for edit rules.
  status: ReceivableStatus;
  effectiveStatus: ReceivableStatus;
  // Negative = days overdue; null when no expected return date was set.
  daysUntilDue: number | null;
  paymentMethod: PaymentMethod;
  notes: string | null;
  createdAt: string;
  updatedAt: string;
  // Present on the detail endpoint only (newest first).
  repayments?: ReceivableRepaymentDTO[];
}

export interface ReceivableSummaryDTO {
  basis: "ACTUAL";
  currency: string;
  totalOutstanding: string;
  activeCount: number;
  dueSoon: { amount: string; count: number; withinDays: number };
  overdue: { amount: string; count: number };
  returnedThisMonth: string;
  largest: { id: string; person: string; outstandingAmount: string } | null;
}

export interface RecordRepaymentResultDTO {
  receivable: ReceivableDTO;
  repayment: ReceivableRepaymentDTO;
  // true when the same idempotencyKey was already recorded: nothing new was written.
  duplicate: boolean;
}

export interface AccountTransferDTO {
  id: string;
  fromAccount: string;
  toAccount: string;
  amount: string;
  currency: string;
  transferredAt: string;
  notes: string | null;
  createdAt: string;
}

// --- Expense flow type, analytics, quick expense, money flow ----------------------------------
// EXPENSE = ordinary spending. OTHER_OUTFLOW = a genuine cash outflow that is not lifestyle
// spending (reduces cash, excluded from expense totals). Investments, emergency-fund money,
// receivables and transfers are separate ledgers, never expense rows.

export type ExpenseFlowType = "EXPENSE" | "OTHER_OUTFLOW";

export interface ExpenseExtremeDTO {
  id: string;
  amount: string;
  spentAt: string;
  merchant: string | null;
  categoryName: string;
}

export interface ExpenseComparisonDTO {
  from: string;
  to: string;
  total: string;
  // current − comparison (negative = spent less).
  change: string;
  // null when the comparison total is zero (nothing to compare against).
  changePercent: number | null;
}

export interface ExpenseAnalyticsDTO {
  basis: "ACTUAL";
  currency: string;
  // `to` is the last INCLUDED day. elapsedDays = days of the range that have happened so far
  // (what averagePerDay divides by).
  period: { from: string; to: string; days: number; elapsedDays: number };
  filters: { categoryId: string | null; flowType: ExpenseFlowType };
  totals: {
    total: string;
    transactionCount: number;
    averagePerTransaction: string | null;
    averagePerDay: string;
    largest: ExpenseExtremeDTO | null;
    smallest: ExpenseExtremeDTO | null;
  };
  // Chosen among days that had spending.
  highestDay: { date: string; total: string } | null;
  lowestDay: { date: string; total: string } | null;
  // Zero-filled up to today (never into the future).
  daily: Array<{ date: string; total: string; count: number }>;
  weekly: Array<{ weekStart: string; total: string; count: number }>;
  monthly: Array<{ month: string; total: string; count: number }>;
  categories: Array<{
    categoryId: string;
    name: string;
    type: string;
    icon: string | null;
    total: string;
    count: number;
    sharePercent: number | null;
    // The same category over the comparison window, and the change vs it (null when it was 0).
    previousTotal: string;
    changePercent: number | null;
  }>;
  // vs the previous calendar month / year for whole months / years, else the previous same-length window.
  comparison: ExpenseComparisonDTO;
  // null unless the same window a year earlier had spending.
  yearOverYear: ExpenseComparisonDTO | null;
  // Present only for a category drill-down: all-category total and this category's share of it.
  overall: { total: string; sharePercent: number | null } | null;
}

export interface ExpensePeriodImpactDTO {
  basis: "ACTUAL";
  date: string;
  flowType: ExpenseFlowType;
  day: { categoryTotal: string; allCategoriesTotal: string };
  month: { categoryTotal: string; allCategoriesTotal: string };
  year: { categoryTotal: string; allCategoriesTotal: string };
}

export interface QuickExpenseResultDTO {
  expense: ExpenseDTO;
  impact: ExpensePeriodImpactDTO;
}

export interface MoneyFlowDTO {
  basis: "ACTUAL";
  period: "MONTHLY";
  asOfDate: string;
  currency: string;
  month: string;
  income: string;
  outflows: { expenses: string; investments: string; emergencyFund: string; receivablesGiven: string; otherOutflow: string };
  // Between the user's own accounts: not income, not an outflow, in no total.
  internalTransfers: string;
  inflows: { receivableRepayments: string; investmentProceeds: string };
  // expenses + investments + emergency fund + receivables given + other outflow (transfers excluded).
  totalGenuineOutflow: string;
  netCashFlow: string;
  percentOfIncome: {
    expenses: number | null;
    investments: number | null;
    emergencyFund: number | null;
    receivablesGiven: number | null;
    otherOutflow: number | null;
  };
  // Ratios (0.25 = 25%), null when no income was recorded.
  savingsRate: string | null;
  investmentRate: string | null;
  expenseRate: string | null;
  dataHealth: Array<{ code: string; severity?: string; message: string; count: number; amount?: string }>;
}

export interface ExpenseSummaryDTO {
  basis: "ACTUAL";
  currency: string;
  date: string;
  flowType: ExpenseFlowType;
  today: string;
  month: string;
  year: string;
}

// --- Emergency fund (ledger rows and the summary the backend already serves) -----------------
export type EmergencyEntryType = "ALLOCATE" | "RELEASE" | "WITHDRAWAL" | "ADJUSTMENT" | "TRANSFER_IN" | "TRANSFER_OUT";

export interface EmergencyFundEntryDTO {
  id: string;
  userId: string;
  type: EmergencyEntryType;
  amount: string;
  occurredAt: string;
  notes: string | null;
  createdAt: string;
  // The source of money added or the reason it was used (short free text).
  reason?: string | null;
}

export interface EmergencyFundSummaryDTO {
  basis: "ACTUAL";
  emergencyCash: string;
  availableCash: string;
  totalCash: string;
  // Emergency Cash / average monthly NEED expenses; null with no essential-expense baseline.
  coverageMonths: string | null;
  avgMonthlyEssentialExpenses: string;
  monthsOfData: number;
}

// --- Recurrence rules & contribution schedules -------------------------------------------------

export interface ExpenseRuleValuesDTO {
  categoryId: string;
  merchant: string | null;
  amount: string;
  paymentMethod: PaymentMethod;
  notes: string | null;
  flowType: ExpenseFlowType;
}

// Which occurrences an edit applies to. THIS = just that row; FUTURE = that row, every later
// already-generated occurrence and the rule for ones not yet generated; RULE (the dedicated
// rule endpoint) = only occurrences not yet generated. Earlier rows are never changed.
export type RecurrenceEditScope = "THIS" | "FUTURE" | "RULE";
export type RecurrenceDeleteMode = "THIS" | "FUTURE";

export interface SipScheduleSummaryDTO {
  investmentId: string;
  active: boolean;
  frequency: Recurrence;
  amountPerPeriod: string | null;
  contributionDay: number | null;
  startDate: string | null;
  endDate: string | null;
  expectedAnnualReturn: string | null;
  // amountPerPeriod expressed per month / per year (e.g. weekly ₹1,000 = ₹4,333.33 / month).
  monthlyEquivalent: string | null;
  annualContribution: string | null;
  // The next date a contribution is due on or after today (null when finished or inactive).
  nextContributionDate: string | null;
  // Occurrences between start and end (null for an open-ended schedule), how many are due so far,
  // and how many remain in the future. Planned total = amountPerPeriod x plannedCount.
  plannedCount: number | null;
  dueSoFarCount: number;
  remainingCount: number | null;
  plannedTotal: string | null;
  // Contributions actually recorded (all CONTRIBUTION cashflows, however they were created).
  actualCount: number;
  actualAmount: string;
}

// --- Investment ledger (cashflows, valuations, metrics) ----------------------------------------
// Mirrors the existing ledger API. Cashflow types keep their financial meaning: a CONTRIBUTION moves
// cash into the investment, a WITHDRAWAL / SALE brings it back, a DIVIDEND is cash income, a FEE is a
// genuine cost, an EMPLOYER_CONTRIBUTION raises the asset without being the user's own cash, INTEREST
// is growth already inside the value, and TRANSFER_IN / TRANSFER_OUT move money between holdings.

export type InvestmentCashflowType =
  | "CONTRIBUTION"
  | "WITHDRAWAL"
  | "SALE"
  | "DIVIDEND"
  | "FEE"
  | "EMPLOYER_CONTRIBUTION"
  | "INTEREST"
  | "TRANSFER_IN"
  | "TRANSFER_OUT";

export interface InvestmentCashflowDTO {
  id: string;
  userId: string;
  investmentId: string;
  type: InvestmentCashflowType;
  amount: string;
  occurredAt: string;
  notes: string | null;
  // MANUAL (typed in), RECURRING (generated by a schedule) or a migration source.
  origin: string;
  periodKey: string | null;
  createdAt?: string;
}

export interface InvestmentValuationDTO {
  id: string;
  userId: string;
  investmentId: string;
  value: string;
  valuedAt: string;
  origin: string;
  createdAt?: string;
}

export interface InvestmentMetricsDTO {
  investmentId: string;
  name: string;
  type: InvestmentType;
  basis: "ACTUAL";
  period: "LIFETIME";
  asOfDate: string;
  // Where currentValue came from: a dated VALUATION, or the legacy currentValue field.
  valuationSource: "VALUATION" | "LEGACY_CURRENT_VALUE";
  grossContributions: string;
  employerContributions: string;
  withdrawals: string;
  netContributions: string;
  costBasis: string;
  currentValue: string;
  unrealizedGain: string;
  realizedGain: string;
  dividends: string;
  fees: string;
  totalReturn: string;
  // A ratio (0.05 = 5%), null when nothing has been invested.
  returnRatio: string | null;
}

// --- Projection (PROJECTED — never an actual, never a guarantee) --------------------------------

export interface ProjectionScenarioDTO {
  years: number;
  // Only the NEW money put in over the horizon.
  totalContributions: string;
  // Current value + total contributions: what would be there with no growth at all.
  principal: string;
  projectedValue: string;
  // projectedValue - principal.
  projectedGain: string;
}

export interface ProjectionCurvePointDTO {
  year: number;
  principal: string;
  projectedValue: string;
}

export interface ProjectionDTO {
  basis: "PROJECTED";
  // Always shown with the numbers: a projection is an assumption, not a promise.
  disclaimer: string;
  assumptions: {
    currentValue: string;
    contributionPerPeriod: string;
    frequency: Recurrence;
    annualReturnPercent: string;
  };
  scenarios: ProjectionScenarioDTO[];
  curve: ProjectionCurvePointDTO[];
}

export interface PortfolioProjectionHoldingDTO {
  id: string;
  name: string;
  type: InvestmentType;
  currentValue: string;
  // The return assumption used for this holding, where it came from, and whether it was projected.
  annualReturnPercent: string | null;
  rateSource: "INVESTMENT" | "DEFAULT" | "NONE";
  contributionPerPeriod: string | null;
  frequency: Recurrence | null;
  included: boolean;
}

export interface PortfolioProjectionDTO {
  basis: "PROJECTED";
  disclaimer: string;
  // The recorded value today (ACTUAL), shown beside — never replaced by — the projection.
  actual: { basis: "ACTUAL"; currentValue: string; holdings: number };
  defaultAnnualReturnPercent: string | null;
  // Sums over the INCLUDED holdings only; excluded ones are listed in `holdings`.
  includedValueToday: string;
  scenarios: ProjectionScenarioDTO[];
  curve: ProjectionCurvePointDTO[];
  holdings: PortfolioProjectionHoldingDTO[];
  includedCount: number;
  excludedCount: number;
}

// --- Investment analytics (ACTUAL, derived from the ledger) --------------------------------------

export interface InvestmentAnalyticsDTO {
  basis: "ACTUAL";
  // Oldest to newest ("2026-05" … "2026-10"), ending with the current month.
  months: string[];
  contributionTrend: Array<{ month: string; contributions: string; employer: string; withdrawals: string }>;
  // Sum of each holding's latest valuation at or before month end; null when none had a valuation yet.
  valueTrend: Array<{ month: string; value: string | null; holdingsValued: number }>;
  // value - net invested, over holdings that have BOTH a ledger and a valuation; null when none do.
  gainTrend: Array<{ month: string; gain: string | null; coveredHoldings: number }>;
  // The CURRENT recorded value split three ways (largest first); percent is of the total, 1 dp.
  allocation: {
    totalValue: string;
    byType: Array<{ key: string; value: string; percent: number }>;
    byRisk: Array<{ key: string; value: string; percent: number }>;
    byLiquidity: Array<{ key: string; value: string; percent: number }>;
  };
  overview: {
    holdings: number;
    holdingsWithLedger: number;
    activeSchedules: number;
    // What the active schedules PLAN to put in (a plan, not what has happened).
    plannedMonthlyContribution: string;
    plannedAnnualContribution: string;
    // What has actually been recorded as the user's own contributions.
    actualContributionsThisMonth: string;
    actualContributionsThisYear: string;
  };
}

// --- Emergency fund overview, ledger and plan --------------------------------------------------
// Balance and coverage are ACTUAL (from the shared financial facts); the target is a TARGET; the
// required contribution and estimated finish date are ESTIMATED planning calculations, not advice.

export interface EmergencyFundLedgerRowDTO {
  id: string;
  type: EmergencyEntryType;
  // As entered (positive, except a signed ADJUSTMENT).
  amount: string;
  // What it did to the reserve: positive adds, negative takes out.
  effect: string;
  // The reserve balance AFTER this entry.
  balanceAfter: string;
  occurredAt: string;
  reason: string | null;
  notes: string | null;
  origin: string;
}

export interface EmergencyFundOverviewDTO {
  basis: "ACTUAL";
  currency: string;
  balance: string;
  coverage: {
    // Balance / average monthly essential expenses; null with no essential-spending history.
    months: string | null;
    avgMonthlyEssentialExpenses: string;
    monthsOfData: number;
  };
  target: {
    basis: "TARGET";
    mode: "AMOUNT" | "MONTHS" | null;
    // The rupee target (for MONTHS: months x average essential spending); null when none is set.
    amount: string | null;
    months: string | null;
    // Months were chosen but there is no spending history yet to turn them into a rupee amount.
    needsExpenseHistory: boolean;
  };
  progress: { percent: number | null; remaining: string | null; reached: boolean };
  plan: {
    basis: "ESTIMATED";
    monthlyContribution: string | null;
    targetDate: string | null;
    // What it would take each month / week to reach the target by the target date.
    requiredMonthly: string | null;
    requiredWeekly: string | null;
    // At the planned monthly contribution: how many months to go, and roughly when.
    monthsToTargetAtPlan: number | null;
    estimatedFinishDate: string | null;
  };
  totals: {
    contributions: string;
    withdrawals: string;
    adjustments: string;
    contributedThisMonth: string;
    contributedThisYear: string;
    withdrawnThisYear: string;
  };
  last: {
    contribution: { date: string; amount: string } | null;
    withdrawal: { date: string; amount: string } | null;
  };
  // Oldest to newest, the last 12 months: balance at month end, money added, money used.
  trend: Array<{ month: string; closingBalance: string; added: string; used: string }>;
  entryCount: number;
}



// --- Batch 8: dashboard overview, detailed reports (all ACTUAL unless labelled) -------------------
export interface DashboardOverviewDTO {
  basis: "ACTUAL";
  asOfDate: string;
  month: string;
  currency: string;
  // Where did this month's money go. The same numbers as the Money Flow endpoint and the reports.
  moneyFlow: MoneyFlowDTO;
  // Ratios as percent (1 dp). null when no income was recorded - never fabricated, never floored.
  savingsRate: number | null;
  investmentRate: number | null;
  expenseRate: number | null;
  expenses: {
    today: string;
    month: string;
    year: string;
    averagePerDay: string;
    essential: string;
    discretionary: string;
    topCategory: { name: string; total: string; sharePercent: number | null } | null;
    largest: ExpenseExtremeDTO | null;
    highestDay: { date: string; total: string } | null;
    comparison: ExpenseComparisonDTO;
  };
  investments: {
    totalValue: string;
    contributedThisMonth: string;
    contributedThisYear: string;
    plannedMonthlyContribution: string;
    activeSchedules: number;
    holdings: number;
  };
  emergencyFund: {
    balance: string;
    targetAmount: string | null;
    progressPercent: number | null;
    coverageMonths: string | null;
    contributedThisMonth: string;
  };
  receivables: {
    outstanding: string;
    activeCount: number;
    dueSoon: { amount: string; count: number; withinDays: number };
    overdue: { amount: string; count: number };
  };
  wealth: {
    netWorth: string;
    availableCash: string;
    emergencyCash: string;
    investments: string;
    receivables: string;
    property: string;
    liabilities: string;
  };
  // Deterministic sentences built from the numbers above. Never produced by an LLM.
  narrative: string[];
  dataHealth: Array<{ code: string; severity?: string; message: string; count: number; amount?: string }>;
}

export interface ReportCategoryRowDTO {
  categoryId: string;
  category: string;
  type: string;
  amount: string;
  percentOfTotal: number | null;
  previousAmount: string;
  changePercent: number | null;
}

export interface MonthlyReportDetailDTO {
  basis: "ACTUAL";
  month: string;
  currency: string;
  moneyFlow: MoneyFlowDTO;
  income: string;
  expenses: string;
  investments: string;
  emergencyFund: string;
  receivablesGiven: string;
  receivableRepayments: string;
  otherOutflow: string;
  internalTransfers: string;
  netCashFlow: string;
  savingsRate: number | null;
  investmentRate: number | null;
  expenseRate: number | null;
  // income - expenses - other outflow. Investments, emergency money and receivables stay assets, so
  // they are not a loss of net worth. Excludes market-value changes and loan principal.
  netWorthChange: { basis: "ESTIMATED"; amount: string; note: string };
  categories: ReportCategoryRowDTO[];
  topCategories: ReportCategoryRowDTO[];
  dailySpending: Array<{ date: string; total: string; count: number }>;
  averagePerDay: string;
  highestDay: { date: string; total: string } | null;
  recurringVsOneTime: { recurring: string; oneTime: string; recurringPercent: number | null };
  largestTransactions: ExpenseExtremeDTO[];
  comparison: ExpenseComparisonDTO;
  narrative: string[];
  dataHealth: Array<{ code: string; severity?: string; message: string; count: number; amount?: string }>;
}

export interface YearlyMonthRowDTO {
  month: string;
  income: string;
  expenses: string;
  investments: string;
  emergencyFund: string;
  receivablesGiven: string;
  otherOutflow: string;
  netCashFlow: string;
  savingsRate: number | null;
}

export interface YearlyMonthsReportDTO {
  basis: "ACTUAL";
  year: number;
  currency: string;
  // January to December, always 12 rows (months with no activity are zero).
  months: YearlyMonthRowDTO[];
  totals: {
    income: string;
    expenses: string;
    investments: string;
    emergencyFund: string;
    receivablesGiven: string;
    otherOutflow: string;
    netCashFlow: string;
    savingsRate: number | null;
  };
  categories: ReportCategoryRowDTO[];
  comparison: ExpenseComparisonDTO;
  highestExpenseMonth: { month: string; total: string } | null;
  lowestExpenseMonth: { month: string; total: string } | null;
  narrative: string[];
}
