import { Injectable } from "@nestjs/common";
import { ClassificationResult } from "./intent-classifier.service";

export interface PlanStep {
  description: string;
}

export interface CoachPlan {
  steps: PlanStep[];
  /** Whether the composed answer needs to go through NumericConsistencyVerifier.
   * Skipped for the deterministic path (CoachService's answer is already fully
   * grounded code, not model output) and for general_search (RagService's own
   * citation-aware synthesis already enforces grounding) — verification is only
   * needed for the intents where AnswerComposerService is generating new prose from
   * gathered facts. */
  needsVerification: boolean;
  /** Whether this path calls the composer at all — general_search uses RagService's
   * own answer directly rather than composing a second time from RAG's output. */
  needsComposition: boolean;
}

// A real, if simple, planning step: not every question needs the same pipeline, and
// this is where that decision is made and recorded (as plain-language plan steps
// that get stored on AgenticCoachRun.plan) rather than left implicit in the
// orchestrator's control flow.
@Injectable()
export class PlannerService {
  buildPlan(classification: ClassificationResult): CoachPlan {
    if (classification.path === "deterministic") {
      return {
        steps: [
          { description: `Matched the deterministic router's "${classification.intent.id}" intent — answering from that service's live data directly.` },
          { description: "Composing a fuller explanation around the grounded answer, without introducing any new figures." },
          { description: "Skipping numeric verification: the base answer is already generated by deterministic code, not by a model." },
        ],
        needsVerification: false,
        needsComposition: true,
      };
    }

    if (classification.intent === "general_search") {
      return {
        steps: [
          { description: "No deterministic intent matched — classified as a general question." },
          { description: "Delegating to AI Search (RAG) to find and cite evidence from the user's own documents, reports, coach history, and alerts." },
          { description: "Using RAG's own citation-aware answer directly — no separate composition step, since RAG already enforces grounding." },
        ],
        needsVerification: false,
        needsComposition: false,
      };
    }

    return {
      steps: [
        { description: `No deterministic intent matched — classified as "${classification.intent}" (confidence ${classification.confidence.toFixed(2)}).` },
        { description: "Gathering the relevant deterministic facts for this category (computed in code, not by the model)." },
        { description: "Composing a natural-language answer strictly from those gathered facts." },
        { description: "Verifying every number in the composed answer traces back to the gathered facts before returning it." },
      ],
      needsVerification: true,
      needsComposition: true,
    };
  }
}
