-- WealthOS AI — initial migration, derived directly from schema.prisma.
--
-- IMPORTANT PROVENANCE NOTE: this file was hand-derived from schema.prisma rather than
-- generated by the real `prisma migrate dev` / `prisma migrate diff` engine. The build
-- environment this was authored in has no network access to binaries.prisma.sh (Prisma's
-- query-engine binary host), so the actual Prisma CLI could not run here — every
-- Prisma command that touches a schema (generate, migrate dev, migrate diff, db push)
-- needs that binary, and none of them could execute.
--
-- Before relying on this in production: run `npx prisma migrate dev` once against a
-- real local database (with real network access) from a clean `migrations/` folder.
-- Prisma will either confirm this SQL matches the schema exactly, or generate a
-- corrective diff migration — both are normal, safe outcomes of that command, not a
-- broken state. See DEPLOYMENT.md for the exact steps.

-- ============================================================================
-- ENUMS
-- ============================================================================

CREATE TYPE "Role" AS ENUM ('OWNER', 'MEMBER');
CREATE TYPE "TaxRegime" AS ENUM ('OLD', 'NEW');
CREATE TYPE "RiskProfile" AS ENUM ('CONSERVATIVE', 'MODERATE', 'AGGRESSIVE');
CREATE TYPE "CategoryType" AS ENUM ('NEED', 'WANT', 'SAVINGS');
CREATE TYPE "IncomeSource" AS ENUM ('SALARY', 'FREELANCE', 'BUSINESS', 'RENT', 'DIVIDEND', 'INTEREST', 'BONUS', 'PENSION', 'OTHER');
CREATE TYPE "Recurrence" AS ENUM ('ONE_TIME', 'WEEKLY', 'MONTHLY', 'QUARTERLY', 'YEARLY');
CREATE TYPE "PaymentMethod" AS ENUM ('CASH', 'UPI', 'CARD', 'BANK_TRANSFER', 'WALLET', 'OTHER');
CREATE TYPE "InvestmentType" AS ENUM ('MUTUAL_FUND', 'STOCK', 'ETF', 'EPF', 'PPF', 'NPS', 'FD', 'BOND', 'GOLD', 'SILVER', 'REAL_ESTATE', 'CRYPTO', 'BUSINESS_EQUITY', 'OTHER');
CREATE TYPE "RiskLevel" AS ENUM ('LOW', 'MODERATE', 'HIGH');
CREATE TYPE "Liquidity" AS ENUM ('LIQUID', 'SEMI_LIQUID', 'ILLIQUID');
CREATE TYPE "LoanType" AS ENUM ('HOME', 'CAR', 'EDUCATION', 'PERSONAL', 'BUSINESS', 'CREDIT_CARD', 'FAMILY', 'OTHER');
CREATE TYPE "InsuranceType" AS ENUM ('HEALTH', 'TERM', 'VEHICLE', 'HOME', 'PERSONAL_ACCIDENT', 'CRITICAL_ILLNESS', 'TRAVEL', 'BUSINESS');
CREATE TYPE "GoalType" AS ENUM ('EMERGENCY_FUND', 'HOUSE', 'LAND', 'CAR', 'MARRIAGE', 'CHILD_EDUCATION', 'RETIREMENT', 'EARLY_RETIREMENT', 'BUSINESS_EXPANSION', 'VACATION', 'HEALTHCARE_RESERVE', 'PASSIVE_INCOME', 'FAMILY_SUPPORT', 'OTHER');
CREATE TYPE "TaxSection" AS ENUM ('SECTION_80C', 'SECTION_80D', 'SECTION_80CCD_1B', 'HRA', 'HOME_LOAN_INTEREST', 'SECTION_80TTA', 'SECTION_80E', 'OTHER');
CREATE TYPE "AlertType" AS ENUM ('EMI_DUE', 'INSURANCE_RENEWAL', 'BUDGET_OVERSPEND', 'GOAL_DELAY', 'SUBSCRIPTION_RENEWAL', 'DEBT_STRESS', 'DOCUMENT_EXPIRY', 'BUSINESS_OBLIGATION_DUE');
CREATE TYPE "AlertSeverity" AS ENUM ('INFO', 'WARNING', 'CRITICAL');
CREATE TYPE "DigestFrequency" AS ENUM ('DAILY', 'WEEKLY', 'OFF');
CREATE TYPE "Theme" AS ENUM ('LIGHT', 'DARK', 'SYSTEM');
CREATE TYPE "AppLanguage" AS ENUM ('EN', 'HI', 'MR');
CREATE TYPE "PropertyType" AS ENUM ('HOUSE', 'APARTMENT', 'PLOT', 'LAND', 'COMMERCIAL', 'RENTAL');
CREATE TYPE "BusinessTransactionType" AS ENUM ('REVENUE', 'EXPENSE', 'OWNER_DRAWING');
CREATE TYPE "DocumentCategory" AS ENUM ('PAN', 'AADHAAR', 'SALARY_SLIP', 'FORM_16', 'INSURANCE_POLICY', 'LOAN_DOCUMENT', 'MF_STATEMENT', 'TAX_RETURN', 'PROPERTY_PAPER', 'BUSINESS_DOCUMENT', 'RECEIPT', 'BILL', 'OTHER');
CREATE TYPE "OcrStatus" AS ENUM ('NOT_APPLICABLE', 'PENDING', 'DONE', 'FAILED');
CREATE TYPE "ScenarioType" AS ENUM ('SALARY_HIKE', 'SALARY_DROP', 'SIP_INCREASE', 'SIP_DECREASE', 'HOUSE_PURCHASE', 'LOAN_PREPAYMENT', 'RETIREMENT_AGE_SHIFT', 'EMERGENCY_EXPENSE', 'GOAL_DELAY');

-- ============================================================================
-- CORE: Household, User, Dependent, Session, OtpCode, Category
-- ============================================================================

CREATE TABLE "Household" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "Household_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "User" (
    "id" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "phone" TEXT,
    "name" TEXT,
    "dateOfBirth" TIMESTAMP(3),
    "role" "Role" NOT NULL DEFAULT 'OWNER',
    "taxRegime" "TaxRegime" NOT NULL DEFAULT 'NEW',
    "riskProfile" "RiskProfile" NOT NULL DEFAULT 'MODERATE',
    "householdId" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");
CREATE UNIQUE INDEX "User_phone_key" ON "User"("phone");
CREATE INDEX "User_householdId_idx" ON "User"("householdId");

CREATE TABLE "Dependent" (
    "id" TEXT NOT NULL,
    "householdId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "relation" TEXT NOT NULL,
    "dateOfBirth" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "Dependent_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "Dependent_householdId_idx" ON "Dependent"("householdId");

CREATE TABLE "Session" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "expiresAt" TIMESTAMP(3) NOT NULL,
    "userAgent" TEXT,
    "ipAddress" TEXT,
    "revoked" BOOLEAN NOT NULL DEFAULT false,
    CONSTRAINT "Session_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "Session_userId_idx" ON "Session"("userId");

CREATE TABLE "OtpCode" (
    "id" TEXT NOT NULL,
    "userId" TEXT,
    "identifier" TEXT NOT NULL,
    "codeHash" TEXT NOT NULL,
    "expiresAt" TIMESTAMP(3) NOT NULL,
    "consumed" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "OtpCode_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "OtpCode_identifier_idx" ON "OtpCode"("identifier");

CREATE TABLE "Category" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "type" "CategoryType" NOT NULL,
    "icon" TEXT,
    "isSystem" BOOLEAN NOT NULL DEFAULT true,
    CONSTRAINT "Category_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "Category_name_key" ON "Category"("name");

CREATE TABLE "Income" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "source" "IncomeSource" NOT NULL,
    "label" TEXT NOT NULL,
    "amount" DECIMAL(14,2) NOT NULL,
    "currency" TEXT NOT NULL DEFAULT 'INR',
    "recurrence" "Recurrence" NOT NULL DEFAULT 'MONTHLY',
    "receivedAt" TIMESTAMP(3) NOT NULL,
    "notes" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "Income_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "Income_userId_receivedAt_idx" ON "Income"("userId", "receivedAt");

CREATE TABLE "Expense" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "categoryId" TEXT NOT NULL,
    "merchant" TEXT,
    "amount" DECIMAL(14,2) NOT NULL,
    "currency" TEXT NOT NULL DEFAULT 'INR',
    "spentAt" TIMESTAMP(3) NOT NULL,
    "paymentMethod" "PaymentMethod" NOT NULL DEFAULT 'UPI',
    "notes" TEXT,
    "isRecurring" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "Expense_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "Expense_userId_spentAt_idx" ON "Expense"("userId", "spentAt");
CREATE INDEX "Expense_categoryId_idx" ON "Expense"("categoryId");

CREATE TABLE "AuditLog" (
    "id" TEXT NOT NULL,
    "userId" TEXT,
    "action" TEXT NOT NULL,
    "metadata" JSONB,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "AuditLog_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "AuditLog_userId_createdAt_idx" ON "AuditLog"("userId", "createdAt");

-- ============================================================================
-- PHASE 2: Goals, Investments, Loans, Insurance
-- ============================================================================

CREATE TABLE "Goal" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "type" "GoalType" NOT NULL,
    "name" TEXT NOT NULL,
    "targetAmount" DECIMAL(14,2) NOT NULL,
    "targetDate" TIMESTAMP(3) NOT NULL,
    "currentAmount" DECIMAL(14,2) NOT NULL DEFAULT 0,
    "monthlyContribution" DECIMAL(14,2) NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "Goal_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "Goal_userId_idx" ON "Goal"("userId");

CREATE TABLE "Investment" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "type" "InvestmentType" NOT NULL,
    "name" TEXT NOT NULL,
    "currentValue" DECIMAL(14,2) NOT NULL,
    "costBasis" DECIMAL(14,2) NOT NULL,
    "purchaseDate" TIMESTAMP(3) NOT NULL,
    "riskLevel" "RiskLevel" NOT NULL DEFAULT 'MODERATE',
    "liquidity" "Liquidity" NOT NULL DEFAULT 'SEMI_LIQUID',
    "goalId" TEXT,
    "notes" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "Investment_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "Investment_userId_idx" ON "Investment"("userId");
CREATE INDEX "Investment_goalId_idx" ON "Investment"("goalId");

CREATE TABLE "Loan" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "type" "LoanType" NOT NULL,
    "lender" TEXT NOT NULL,
    "principal" DECIMAL(14,2) NOT NULL,
    "outstandingPrincipal" DECIMAL(14,2) NOT NULL,
    "interestRateAnnual" DECIMAL(5,2) NOT NULL,
    "tenureMonths" INTEGER NOT NULL,
    "emiAmount" DECIMAL(14,2) NOT NULL,
    "startDate" TIMESTAMP(3) NOT NULL,
    "notes" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "Loan_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "Loan_userId_idx" ON "Loan"("userId");

CREATE TABLE "InsurancePolicy" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "type" "InsuranceType" NOT NULL,
    "provider" TEXT NOT NULL,
    "policyNumber" TEXT,
    "premiumAmount" DECIMAL(14,2) NOT NULL,
    "premiumFrequency" "Recurrence" NOT NULL DEFAULT 'YEARLY',
    "coverageAmount" DECIMAL(14,2) NOT NULL,
    "renewalDate" TIMESTAMP(3) NOT NULL,
    "nomineeName" TEXT,
    "notes" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "InsurancePolicy_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "InsurancePolicy_userId_idx" ON "InsurancePolicy"("userId");

-- ============================================================================
-- PHASE 3: Tax, Retirement, Alerts, Settings
-- ============================================================================

CREATE TABLE "TaxDeduction" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "section" "TaxSection" NOT NULL,
    "description" TEXT NOT NULL,
    "amount" DECIMAL(12,2) NOT NULL,
    "financialYear" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "TaxDeduction_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "TaxDeduction_userId_financialYear_idx" ON "TaxDeduction"("userId", "financialYear");

CREATE TABLE "RetirementProfile" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "targetRetirementAge" INTEGER NOT NULL DEFAULT 60,
    "desiredMonthlyIncomeToday" DECIMAL(12,2) NOT NULL,
    "inflationRatePercent" DECIMAL(5,2) NOT NULL DEFAULT 6,
    "expectedReturnPreRetirementPercent" DECIMAL(5,2) NOT NULL DEFAULT 11,
    "expectedReturnPostRetirementPercent" DECIMAL(5,2) NOT NULL DEFAULT 7,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "RetirementProfile_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "RetirementProfile_userId_key" ON "RetirementProfile"("userId");

CREATE TABLE "Alert" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "type" "AlertType" NOT NULL,
    "severity" "AlertSeverity" NOT NULL DEFAULT 'INFO',
    "title" TEXT NOT NULL,
    "message" TEXT NOT NULL,
    "dedupeKey" TEXT NOT NULL,
    "dueDate" TIMESTAMP(3),
    "isRead" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "Alert_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "Alert_userId_dedupeKey_key" ON "Alert"("userId", "dedupeKey");
CREATE INDEX "Alert_userId_isRead_idx" ON "Alert"("userId", "isRead");

CREATE TABLE "UserSettings" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "notifyEmail" BOOLEAN NOT NULL DEFAULT true,
    "digestFrequency" "DigestFrequency" NOT NULL DEFAULT 'WEEKLY',
    "theme" "Theme" NOT NULL DEFAULT 'LIGHT',
    "language" "AppLanguage" NOT NULL DEFAULT 'EN',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "UserSettings_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "UserSettings_userId_key" ON "UserSettings"("userId");

-- ============================================================================
-- PHASE 4: Property, Business, Documents
-- ============================================================================

CREATE TABLE "Property" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "type" "PropertyType" NOT NULL,
    "name" TEXT NOT NULL,
    "address" TEXT,
    "currentValue" DECIMAL(14,2) NOT NULL,
    "purchasePrice" DECIMAL(14,2) NOT NULL,
    "purchaseDate" TIMESTAMP(3) NOT NULL,
    "isRented" BOOLEAN NOT NULL DEFAULT false,
    "monthlyRentalIncome" DECIMAL(12,2),
    "annualMaintenanceCost" DECIMAL(12,2) NOT NULL DEFAULT 0,
    "annualPropertyTax" DECIMAL(12,2) NOT NULL DEFAULT 0,
    "loanId" TEXT,
    "insurancePolicyId" TEXT,
    "notes" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "Property_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "Property_userId_idx" ON "Property"("userId");
CREATE INDEX "Property_loanId_idx" ON "Property"("loanId");
CREATE INDEX "Property_insurancePolicyId_idx" ON "Property"("insurancePolicyId");

CREATE TABLE "Business" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "Business_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "Business_userId_idx" ON "Business"("userId");

CREATE TABLE "BusinessTransaction" (
    "id" TEXT NOT NULL,
    "businessId" TEXT NOT NULL,
    "type" "BusinessTransactionType" NOT NULL,
    "category" TEXT,
    "amount" DECIMAL(14,2) NOT NULL,
    "occurredAt" TIMESTAMP(3) NOT NULL,
    "description" TEXT,
    "isRecurring" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "BusinessTransaction_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "BusinessTransaction_businessId_occurredAt_idx" ON "BusinessTransaction"("businessId", "occurredAt");

CREATE TABLE "BusinessObligation" (
    "id" TEXT NOT NULL,
    "businessId" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "dueDate" TIMESTAMP(3) NOT NULL,
    "amount" DECIMAL(12,2),
    "recurrence" "Recurrence" NOT NULL DEFAULT 'MONTHLY',
    "notes" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "BusinessObligation_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "BusinessObligation_businessId_dueDate_idx" ON "BusinessObligation"("businessId", "dueDate");

CREATE TABLE "Document" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "category" "DocumentCategory" NOT NULL,
    "fileName" TEXT NOT NULL,
    "mimeType" TEXT NOT NULL,
    "sizeBytes" INTEGER NOT NULL,
    "storageKey" TEXT NOT NULL,
    "tags" TEXT[],
    "expiryDate" TIMESTAMP(3),
    "ocrStatus" "OcrStatus" NOT NULL DEFAULT 'NOT_APPLICABLE',
    "ocrText" TEXT,
    "summary" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "Document_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "Document_userId_category_idx" ON "Document"("userId", "category");
CREATE INDEX "Document_userId_expiryDate_idx" ON "Document"("userId", "expiryDate");

-- ============================================================================
-- PHASE 5: AI Coach, What-If Simulator
-- ============================================================================

CREATE TABLE "CoachInteraction" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "question" TEXT NOT NULL,
    "matchedIntent" TEXT,
    "answer" TEXT NOT NULL,
    "dataSources" TEXT[],
    "wasRefused" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "CoachInteraction_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "CoachInteraction_userId_createdAt_idx" ON "CoachInteraction"("userId", "createdAt");

CREATE TABLE "SavedScenario" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "scenarioType" "ScenarioType" NOT NULL,
    "label" TEXT NOT NULL,
    "params" JSONB NOT NULL,
    "resultSnapshot" JSONB NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "SavedScenario_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "SavedScenario_userId_createdAt_idx" ON "SavedScenario"("userId", "createdAt");

-- ============================================================================
-- FOREIGN KEYS
-- ============================================================================

ALTER TABLE "User" ADD CONSTRAINT "User_householdId_fkey" FOREIGN KEY ("householdId") REFERENCES "Household"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Dependent" ADD CONSTRAINT "Dependent_householdId_fkey" FOREIGN KEY ("householdId") REFERENCES "Household"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Session" ADD CONSTRAINT "Session_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "OtpCode" ADD CONSTRAINT "OtpCode_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Income" ADD CONSTRAINT "Income_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Expense" ADD CONSTRAINT "Expense_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Expense" ADD CONSTRAINT "Expense_categoryId_fkey" FOREIGN KEY ("categoryId") REFERENCES "Category"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "AuditLog" ADD CONSTRAINT "AuditLog_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Goal" ADD CONSTRAINT "Goal_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Investment" ADD CONSTRAINT "Investment_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Investment" ADD CONSTRAINT "Investment_goalId_fkey" FOREIGN KEY ("goalId") REFERENCES "Goal"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Loan" ADD CONSTRAINT "Loan_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "InsurancePolicy" ADD CONSTRAINT "InsurancePolicy_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "TaxDeduction" ADD CONSTRAINT "TaxDeduction_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "RetirementProfile" ADD CONSTRAINT "RetirementProfile_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Alert" ADD CONSTRAINT "Alert_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "UserSettings" ADD CONSTRAINT "UserSettings_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Property" ADD CONSTRAINT "Property_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Property" ADD CONSTRAINT "Property_loanId_fkey" FOREIGN KEY ("loanId") REFERENCES "Loan"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Property" ADD CONSTRAINT "Property_insurancePolicyId_fkey" FOREIGN KEY ("insurancePolicyId") REFERENCES "InsurancePolicy"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Business" ADD CONSTRAINT "Business_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "BusinessTransaction" ADD CONSTRAINT "BusinessTransaction_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "Business"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "BusinessObligation" ADD CONSTRAINT "BusinessObligation_businessId_fkey" FOREIGN KEY ("businessId") REFERENCES "Business"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Document" ADD CONSTRAINT "Document_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "CoachInteraction" ADD CONSTRAINT "CoachInteraction_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "SavedScenario" ADD CONSTRAINT "SavedScenario_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
